### ISSUE TITLE
Conflicting SysLogHandler in ocrd_logging.conf

### ISSUE THREAD

**Issue by markusweigelt** [slub/ocrd_manager#68]
Following error occurs when running `make test`

```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ocrd/cli/workspace.py", line 61, in workspace_cli
    initLogging()
  File "/usr/local/lib/python3.8/site-packages/ocrd_utils/logging.py", line 112, in initLogging
    logging.getLogger('').critical('initLogging was called multiple times. Source of latest call:')
Message: 'initLogging was called multiple times. Source of latest call:'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ocrd/cli/workspace.py", line 61, in workspace_cli
    initLogging()
  File "/usr/local/lib/python3.8/site-packages/ocrd_utils/logging.py", line 114, in initLogging
    logging.getLogger('').critical(line)
Message: '  File "/usr/local/lib/python3.8/site-packages/ocrd/cli/workspace.py", line 61, in workspace_cli'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 934, in emit
    self.socket.send(msg)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 855, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/handlers.py", line 937, in emit
    self._connect_unixsocket(self.address)
  File "/usr/lib/python3.8/logging/handlers.py", line 866, in _connect_unixsocket
    self.socket.connect(address)
FileNotFoundError: [Errno 2] No such file or directory
Call stack:
  File "/usr/local/bin/ocrd", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1685, in invoke
    super().invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/ocrd/cli/workspace.py", line 61, in workspace_cli
    initLogging()
  File "/usr/local/lib/python3.8/site-packages/ocrd_utils/logging.py", line 114, in initLogging
    logging.getLogger('').critical(line)
Message: '    initLogging()'
Arguments: ()
```

The temporary solution is to replace the handler with a NullHandler. https://github.com/slub/ocrd_manager/blob/df6cec120a465750d0b10a5d05d5d8501de323db/ocrd_logging.conf#L95-L102

**Comment by bertsky** [comment]
> Following error occurs when running `make test`
...

Sounds like we got a problem with rsyslog not providing /dev/log anymore.


> The temporary solution was to replace the handler with a NullHandler.

We do need logging though, I'll revert and try to get the true problem fixed...

**Comment by bertsky** [comment]
Ok, so the reason for this error is quite simple: you ran some OCR-D command before starting the syslog service (rsyslogd creates /dev/log). Do you still remember in what context you called `make test`?

**Comment by markusweigelt** [comment]
> Do you still remember in what context you called `make test`?

Yes the context was calling `make test` in `ocrd_kitodo` repositories `makefile-ci` workflow.

**Comment by bertsky** [comment]
> Yes the context was calling `make test` of `makefile-ci` workflow in `ocrd_kitodo` repository.

Strange! It should rely on a rully initialised Manager (i.e. after having run startup.sh, which does up rsyslogd).

Do you remember how the test identifies its Manager instance, does it echo `using ocrd@localhost` or `using ocrd_kitodo-ocrd-manager-1`?

**Comment by markusweigelt** [comment]
As far as I can see (https://github.com/slub/ocrd_manager/blob/e8c06e0e0a71a4249394f3f3790c3dbcc0e5fdbf/Makefile#L93C1-L93C25 and https://github.com/slub/ocrd_manager/blob/e8c06e0e0a71a4249394f3f3790c3dbcc0e5fdbf/Makefile#L109), the test depends on checking the network, so I assume it's running under ocrd@localhost.

**Comment by bertsky** [comment]
> the test depends on checking the network, so I assume it's running under `ocrd@localhost`.

yes, and as per [ocrd_kitodo's `make test`](https://github.com/slub/ocrd_kitodo/blob/34e8038a810a87106bea2b9450373ca8d53e3383/Makefile#L188), this will be the one controlled by Docker Compose. So it tries to log into the existing SSH servers instead of docker execing into the container. But in either case, the container should have a running rsyslog... still puzzled!
